name: neuralprophet_env
channels:
  - defaults

dependencies:
  - python=3.10
  - ipykernel
  - tqdm
  - statsmodels
  - requests
  - matplotlib
  - numpy
  - pandas
  - scipy
  - seaborn
  - jinja2
  - jupyter
  - jupyterlab-github
  - jupyterlab-git
  - jupytext
  - xgboost
  - scikit-learn
  - watchdog
  - pip:
    - neuralprophet
