name: neuralprophet_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyter
  - jupyterlab
  - jupyterlab-git
  - jupytext
  - tqdm
  - numpy
  - pandas
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - requests
  - jinja2
  - watchdog
  - pip:
    - neuralprophet
